### ISSUE TITLE
Consider moving away from hosting your artifacts on JCenter, as it's being decommissioned

### ISSUE THREAD

**Issue by carlspring** [Netflix/dgs-framework#116]
# Task Description

You should consider moving away from hosting your artifacts on JCenter as soon as possible, as it's being decommissioned.

Please, have a look at these links:
* https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
* https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

# Task List

* [ ] Re-publish all releases to Maven Central.
* [ ] Make all future releases to Maven Central.
* [ ] Update the documentation and the examples.

**Comment by paulbakker** [comment]
Already done :) 
Removed the jcenter repository here after upgrading the one and only dependency we needed from there: https://github.com/Netflix/dgs-framework/pull/91

And updated the publication action, which is based on the NetflixOSS plugin which has been updated.

We're not planning to re-publish old artifacts. There's another year where folks can pull from jcenter (but not push), so if they need some more time before upgrading the DGS version they can.

**Comment by carlspring** [comment]
Ah, great! The docs I was reading were poiting to the jcenter repository, which is why I thought I should let you know. Great to hear you've already migrated! :)

**Comment by paulbakker** [comment]
Oh, yes, we do need to remove that from the docs. I'll do that. Thanks for reporting that.
